### PR TITLE
Adds possibility for instructors to view students code

### PR DESCRIPTION
**Pull request by dz0**
solves https://github.com/daveagp/websheets/issues/7

But I tested it with fake login (no auth providers), 
and as I checked it with no login -- it doesn't load anything.

### CODE REVIEW

**Comment by daveagp** [comment]
I hope to try this in the next couple of days. I'm not clear about what you mean in your comment "I checked it with no login -- it doesn't load anything." Does that mean it's impossible to test?

**Comment by dz0** [comment]
It works for me when I hacked fake user in auth.php.

But otherwise, because no "auth" providers are defined, some javascript err
get's in the way..
so I didn't test it for anonymous user...

On Fri, Jan 15, 2016 at 8:41 AM, Dave Pritchard <notifications@github.com>
wrote:

> I hope to try this in the next couple of days. I'm not clear about what
> you mean in your comment "I checked it with no login -- it doesn't load
> anything." Does that mean it's impossible to test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daveagp/websheets/pull/10#issuecomment-171883671>.
>



-- 
Jurgis Pralgauskis
tel: 8-616 77613;
Don't worry, be happy and make things better ;)
http://galvosukykla.lt

**Comment by dz0** [comment]
I mean, I couldn't check if it has some side effect for anonymous user...

On Fri, Jan 15, 2016 at 9:29 AM, Jurgis Pralgauskis <
jurgis.pralgauskis@gmail.com> wrote:

> It works for me when I hacked fake user in auth.php.
>
> But otherwise, because no "auth" providers are defined, some javascript
> err get's in the way..
> so I didn't test it for anonymous user...
>
> On Fri, Jan 15, 2016 at 8:41 AM, Dave Pritchard <notifications@github.com>
> wrote:
>
>> I hope to try this in the next couple of days. I'm not clear about what
>> you mean in your comment "I checked it with no login -- it doesn't load
>> anything." Does that mean it's impossible to test?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/daveagp/websheets/pull/10#issuecomment-171883671>.
>>
>
>
>
> --
> Jurgis Pralgauskis
> tel: 8-616 77613;
> Don't worry, be happy and make things better ;)
> http://galvosukykla.lt
>



-- 
Jurgis Pralgauskis
tel: 8-616 77613;
Don't worry, be happy and make things better ;)
http://galvosukykla.lt

**Comment by daveagp** [comment]
I tried this out and read the code. Looks like it works, and it's very elegant! I checked that you can't accidentally overwrite the student's code. Thanks!!! :sun_with_face:

**Pull request merged**
